from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from .chunk import RetrievedChunk


class AgentResponse(BaseModel):
    """The final answer generated by the OpenAI Agent based on retrieved context, containing both the answer and source attribution"""

    response_id: str = Field(..., description="Unique identifier for the response")
    query_id: str = Field(..., description="Reference to the original query")
    answer: str = Field(..., description="The generated answer text")
    source_chunks: Optional[List[RetrievedChunk]] = Field(None, description="List of chunks that informed the response")
    confidence_level: Optional[float] = Field(None, description="Confidence score for the response (-1.0 to 1.0)", ge=-1.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.now, description="When the response was generated")
    has_sources: bool = Field(..., description="Whether the response was generated from retrieved sources")


class SourceChunk(BaseModel):
    """Model for the source chunk in the API response"""

    chunk_id: str = Field(..., description="Unique identifier for the document chunk")
    content: str = Field(..., description="The text content of the retrieved chunk")
    document_id: str = Field(..., description="Identifier of the source document")
    similarity_score: float = Field(..., description="Similarity score from vector search (-1.0 to 1.0)", ge=-1.0, le=1.0)
    metadata: Optional[dict] = Field(None, description="Additional metadata about the chunk")


class APIResponse(BaseModel):
    """API response model for the chat endpoint"""

    response_id: str = Field(..., description="Unique identifier for this response")
    query_id: Optional[str] = Field(None, description="Identifier of the original query")
    answer: str = Field(..., description="The generated answer to the user's query")
    sources: List[SourceChunk] = Field(default=[], description="List of document chunks that informed the response")
    has_sources: bool = Field(..., description="Whether the response was generated from retrieved sources")
    confidence: Optional[float] = Field(None, description="Confidence level of the response (0.0 to 1.0)", ge=0.0, le=1.0)
    timestamp: datetime = Field(default_factory=datetime.now, description="When the response was generated")