from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import logging
import uuid
import uvicorn
from datetime import datetime
import json

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Data models
class QueryRequest(BaseModel):
    query: str
    context: Optional[str] = None
    session_id: Optional[str] = None

class Source(BaseModel):
    id: str
    title: str
    content: str
    page_reference: str

class QueryResponse(BaseModel):
    response: str
    sources: List[Source]
    status: str
    session_id: str
    error_message: Optional[str] = None

class HealthResponse(BaseModel):
    status: str
    service: str
    timestamp: str

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage the application lifecycle"""
    logger.info("Starting up RAG service...")
    yield
    logger.info("Shutting down RAG service...")

# Create FastAPI app with lifespan
app = FastAPI(
    title="Simple RAG Chat API",
    description="Simplified API for RAG (Retrieval Augmented Generation) chat functionality",
    version="1.0.0",
    lifespan=lifespan
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, replace with specific origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/api/rag/health", response_model=HealthResponse)
async def health_check():
    """Health check endpoint"""
    return HealthResponse(
        status="healthy",
        service="RAG backend",
        timestamp=datetime.now().isoformat()
    )

@app.post("/api/rag/query", response_model=QueryResponse)
async def query_endpoint(request: QueryRequest):
    """Submit a query to the RAG system and receive a response"""
    try:
        # Validate the request
        if not request.query or len(request.query) < 1 or len(request.query) > 1000:
            raise HTTPException(status_code=422, detail="Query must be between 1 and 1000 characters")

        if request.context and (len(request.context) < 1 or len(request.context) > 5000):
            raise HTTPException(status_code=422, detail="Context must be between 1 and 5000 characters if provided")

        # Generate or validate session ID
        session_id = request.session_id or str(uuid.uuid4())

        # Validate session ID format if provided
        if request.session_id:
            try:
                uuid.UUID(request.session_id)
                session_id = request.session_id
            except ValueError:
                raise HTTPException(status_code=422, detail="Session ID must be a valid UUID if provided")

        # Process the query - simplified implementation
        response_text = f"I understand you're asking about: '{request.query}'. "

        if request.context:
            response_text += f"Based on the context you provided ('{request.context[:50]}...'), "
            response_text += "I can provide more specific information. "

        response_text += "This is a simulated response from the RAG system. In a full implementation, this would be generated by an AI model based on the book content."

        # Create mock sources using Source model
        sources = [
            Source(
                id="mock-source-1",
                title="ROS 2: Robotic Nervous System",
                content="This is sample book content related to your query.",
                page_reference="Chapter 1, Page 10"
            )
        ]

        result = {
            "response": response_text,
            "sources": sources,
            "status": "SUCCESS",
            "session_id": session_id
        }

        return QueryResponse(**result)

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error processing query: {str(e)}")
        return QueryResponse(
            response="",
            sources=[],
            status="ERROR",
            session_id=request.session_id or str(uuid.uuid4()),
            error_message=str(e)
        )

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)